### ISSUE TITLE
프로젝트 구조 및 마일스톤 설정

### ISSUE THREAD

**Issue by devKangMinHyeok** [libre-flux/auth-flow#1]
### long term purpose
1. rbac, abac 등 권한 관리를 쉽고 안전하게 유지보수할 수 있는 라이브러리 제작 
2. multi-project에서, 권한 관리에 대해 정의된 single source를 통해, 권한 관리 동기화를 보장할 수 있는 라이브러리 제작

### short term purpose
js, ts, react에서 rbac을 관리할 수 있는 라이브러리 제작
1. core
2. react-plugin

### TODO
- [ ] 라이브러리 아키텍처 설계
- [ ] monorepo 세팅
- [ ] core lib 제작
- [ ] react-plugin 제작
- [ ] docs 제작
- [ ] ci/cd 파이프라인 제작
